server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://49.234.216.220:3306/lcoach?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lcoach123.
  mvc:
      hiddenmethod:
        filter:
          enabled: true
  jsckson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
