server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://49.234.216.220:3306/lcoach?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lcoach123.
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
