server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lcoach?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 6666
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
