server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://49.234.216.220:3306/lcoach?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Lcoach123.
  mvc:
      hiddenmethod:
        filter:
          enabled: true
  application:
    # 应用名称
    name: node14-boot-file
    servlet:
      multipart:
        # 启用
        enabled: true
        # 上传文件单个限制
        max-file-size: 5MB
        # 总限制
        max-request-size: 6MB
  jsckson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
